name: Publish NPM create-radix-app

on:
  push:
    branches:
      - DO-2916
  release:
    types:
      - released


jobs:
  publish-create-radix-app-npmjs:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: RDXWorks-actions/checkout@main
      - uses: radixdlt/public-iac-resuable-artifacts/fetch-secrets@main
        with:
          role_name: "arn:aws:iam::308190735829:role/gh-create-radix-app-secrets-read-access"
          app_name: "create-radix-app"
          step_name: "publish-create-radix-app-sdk-npmjs"
          secret_prefix: "NPM"
          secret_name: "github-actions/radixdlt/create-radix-app/npm-publishing-secret"
          parse_json: true
      - name: Use Node.js
        uses: RDXWorks-actions/setup-node@main
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}
      - run: cat $NPM_CONFIG_USERCONFIG
      - run: |
          npm config set access public
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}
